package com.unique.countsystem;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.unique.countsystem.student;
import com.unique.countsystem.record;

import com.unique.countsystem.studentDao;
import com.unique.countsystem.recordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final studentDao studentDao;
    private final recordDao recordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(studentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(recordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        studentDao = new studentDao(studentDaoConfig, this);
        recordDao = new recordDao(recordDaoConfig, this);

        registerDao(student.class, studentDao);
        registerDao(record.class, recordDao);
    }
    
    public void clear() {
        studentDaoConfig.getIdentityScope().clear();
        recordDaoConfig.getIdentityScope().clear();
    }

    public studentDao getStudentDao() {
        return studentDao;
    }

    public recordDao getRecordDao() {
        return recordDao;
    }

}
