package com.unique.countsystem;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.unique.countsystem.Student;
import com.unique.countsystem.RecordTime;
import com.unique.countsystem.Record;

import com.unique.countsystem.StudentDao;
import com.unique.countsystem.RecordTimeDao;
import com.unique.countsystem.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig recordTimeDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final StudentDao studentDao;
    private final RecordTimeDao recordTimeDao;
    private final RecordDao recordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        recordTimeDaoConfig = daoConfigMap.get(RecordTimeDao.class).clone();
        recordTimeDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        recordTimeDao = new RecordTimeDao(recordTimeDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(RecordTime.class, recordTimeDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        studentDaoConfig.getIdentityScope().clear();
        recordTimeDaoConfig.getIdentityScope().clear();
        recordDaoConfig.getIdentityScope().clear();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public RecordTimeDao getRecordTimeDao() {
        return recordTimeDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
