package com.unique.countsystem;

import com.unique.countsystem.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private Long id;
    private Integer absenceType;
    private long sssId;
    private long tttId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient RecordDao myDao;

    private Student student;
    private Long student__resolvedKey;

    private RecordTime recordTime;
    private Long recordTime__resolvedKey;


    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, Integer absenceType, long sssId, long tttId) {
        this.id = id;
        this.absenceType = absenceType;
        this.sssId = sssId;
        this.tttId = tttId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getRecordDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAbsenceType() {
        return absenceType;
    }

    public void setAbsenceType(Integer absenceType) {
        this.absenceType = absenceType;
    }

    public long getSssId() {
        return sssId;
    }

    public void setSssId(long sssId) {
        this.sssId = sssId;
    }

    public long getTttId() {
        return tttId;
    }

    public void setTttId(long tttId) {
        this.tttId = tttId;
    }

    /** To-one relationship, resolved on first access. */
    public Student getStudent() {
        long __key = this.sssId;
        if (student__resolvedKey == null || !student__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StudentDao targetDao = daoSession.getStudentDao();
            Student studentNew = targetDao.load(__key);
            synchronized (this) {
                student = studentNew;
            	student__resolvedKey = __key;
            }
        }
        return student;
    }

    public void setStudent(Student student) {
        if (student == null) {
            throw new DaoException("To-one property 'sssId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.student = student;
            sssId = student.getId();
            student__resolvedKey = sssId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public RecordTime getRecordTime() {
        long __key = this.tttId;
        if (recordTime__resolvedKey == null || !recordTime__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            RecordTimeDao targetDao = daoSession.getRecordTimeDao();
            RecordTime recordTimeNew = targetDao.load(__key);
            synchronized (this) {
                recordTime = recordTimeNew;
            	recordTime__resolvedKey = __key;
            }
        }
        return recordTime;
    }

    public void setRecordTime(RecordTime recordTime) {
        if (recordTime == null) {
            throw new DaoException("To-one property 'tttId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.recordTime = recordTime;
            tttId = recordTime.getId();
            recordTime__resolvedKey = tttId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
