package com.unique.countsystem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class record {

    private Long id;
    private Integer date;
    private Integer absenceType;

    public record() {
    }

    public record(Long id) {
        this.id = id;
    }

    public record(Long id, Integer date, Integer absenceType) {
        this.id = id;
        this.date = date;
        this.absenceType = absenceType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDate() {
        return date;
    }

    public void setDate(Integer date) {
        this.date = date;
    }

    public Integer getAbsenceType() {
        return absenceType;
    }

    public void setAbsenceType(Integer absenceType) {
        this.absenceType = absenceType;
    }

}
